# Generated by Django 5.1.3 on 2024-11-19 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Скоро начнется'), (2, 'Идет конкурс'), (3, 'Архив')], null=True)),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderator_contests', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы')),
            ],
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField()),
                ('award_description', models.TextField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contestparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.contest')),
                ('experts', models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='expert_stages', to=settings.AUTH_USER_MODEL, verbose_name='Эксперты')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_points', models.IntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='main.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.criterion')),
                ('expert', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.submission')),
            ],
            options={
                'unique_together': {('expert', 'submission', 'criterion')},
            },
        ),
    ]
